INSERT INTO `actors` (`actor_name`)
VALUES
    ('	Anne Hathaway	'),
    ('	Billy Zane	'),
    ('	Bob Gunton	'),
    ('	Brad Pitt	'),
    ('	Burt Young	'),
    ('	Daryl Hannah	'),
    ('	David Carradine	'),
    ('	David Morse	'),
    ('	Jessica Chastain	'),
    ('	John Travolta	'),
    ('	Kate Winslet	'),
    ('	Kevin Spacey	'),
    ('	Kieran Culkin	'),
    ('	Leonardo DiCaprio	'),
    ('	Mary Elizabeth Winstead	'),
    ('	Matthew McConaughey	'),
    ('	Michael Cera	'),
    ('	Michael Clarke Duncan	'),
    ('	Morgan Freeman	'),
    ('	Samuel L. Jackson	'),
    ('	Sylvester Stallone	'),
    ('	Talia Shire	'),
    ('	Tom Hanks	'),
    ('	Uma Thurman	'),
    ('	Tim Robbins	');